
services:
  fedi-streaks:
    build: .
    env_file: .env
    develop:
      watch:
        - path: main.py
          action: rebuild
        - path: requirements.txt
          action: rebuild
  postgres:
    image: postgres:latest
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data